kind: Pod
apiVersion: v1 
metadata:
  name: pods
  labels:
    env: dev
    proj: dummy
spec:
 containers:
  - name: nginx
    image: nginx
    resources:
      requests: 
        cpu: "200m"
        memory: "500Mi"
      limits:
       cpu: "250m"
       memory: "600Mi"
    ports:
    - containerPort: 80
    